language: java

services:
  - docker

stages:
 - name: build
   ./mvnw clean install -Pprod
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   ./mvnw dockerfile:build
 - name: push
   if: branch = master
  ./mvnw dockerfile:push






