info:
  project:
    version: @project.version@

server:
  port: 8787
  servlet:
    context-path: /api


spring:
#  profiles:
#    active: @profile@
  application:
    name: gateway

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  instance:
    appname: gateway
    prefer-ip-address: true
    instanceId: gateway:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: ${info.project.version}

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 60000

zuul: # those values must be configured depending on the application specific needs
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  semaphore:
    max-semaphores: 500
  routes:
    atendimento:
      path: /atendimento/**
      sensitiveHeaders: Set-Cookie
    security:
      path: /security/**
      sensitiveHeaders: Set-Cookie

